### ISSUE TITLE
Check and fix buttons if they are not working properly

### ISSUE THREAD

**Issue by Satkar312** [Brabim21/Hostel_Management_System#37]
Make buttons lead to destination page and fix other ones that are not clickable

**Comment by Ganeshparajuli2059** [comment]
In the staff section the button was not working properly however there was code the only problem was it was not working as user want so this is solved now. 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/248918cc-bb6d-418d-8a35-cabb27549dda)
