### ISSUE TITLE
Add warmer colors to landing page to make it easier on the eyes

### ISSUE THREAD

**Issue by Satkar312** [Brabim21/Hostel_Management_System#39]
Make the landing page easier on the eyes and add low gradient scalars rather than bright colors like red while removing the background

**Comment by Brabim21** [comment]
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/5d44df76-a35f-4696-bf09-bcc8682d8cc6)
Now the landing page is easier on the eyes and added with low gradient scalars rather than bright colors
