### ISSUE TITLE
Fix Layout Issues and Add Missing Features to Event Calendar Section

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#47]
The event calendar is inconveniently placed at the bottom, event details are separated at the top-left, and crucial features like "Edit" and "Update" buttons are missing, along with the option to add events to personal calendars. This layout and functionality hinder the system's usability and efficiency.

The attached screenshot clearly shows all the issues mentioned: 

![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/df8dabf8-a10a-40e9-92a1-a4b4e4cb24e5)

**Comment by Brabim21** [comment]
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/5f7fb99d-0ac0-4225-ae1e-3245538256f2)
Event calendar is now modified as requested with changes in css
