### ISSUE TITLE
Forgot Password Functionality Incorrectly Marks Valid Emails as Invalid

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#48]
The "Forgot Password" feature in our system is currently malfunctioning. Even when users enter a correct email address that exists in the database, the system erroneously reports it as "invalid." This issue prevents users from proceeding with password recovery.

The attached screenshot clearly demonstrates the issue with the "Forgot Password" feature:

![unnamed](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/d3c81f61-082d-44ca-95c1-7af24b64dcb9)
![unnamed](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/ac2be49d-adf5-4a7a-bf18-ee9035ce033a)

**Comment by rojan-dhungel** [comment]
forgot password functionality has been issue has been tackled.
Process:
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/b817963e-db13-48b3-abfe-9156a14dabcc)

Conformation
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/c8d60498-6c30-4cbe-87bf-a3447802cf62)

Database Proof
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/768faf4f-eead-4889-abd9-6d3a630286f4)
