### ISSUE TITLE
View/Update and Delete Buttons Inoperative for Resident Details

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#49]
The backend functionality responsible for handling the "View/Update" and "Delete" actions for resident details is currently non-functional. Despite clicking on these buttons, no action is performed, and there is no error message displayed to indicate the issue. This prevents administrators from effectively accessing and managing resident information.

The attached screenshot illustrates the issue with the "View/Update" and "Delete" buttons:

![unnamed](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/a130266f-9a41-4b70-924f-b8fb30443c5c)

**Comment by Ganeshparajuli2059** [comment]
the button works properly now as before even after clicking it was not working properly.
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/fd22385b-0499-4609-af47-e82af0525091)
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/4c6a5b3f-f9d7-413c-80ff-b7ccd2a2a8e2)
