### ISSUE TITLE
search button not working 

### ISSUE THREAD

**Issue by Satkar312** [Brabim21/Hostel_Management_System#51]
search button is not working as intended
![unnamed](https://github.com/Brabim21/Hostel_Management_System/assets/119673746/7d042c63-7df0-4951-aceb-30ecb0fd21e5)

**Comment by rojan-dhungel** [comment]
Asking for request:
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/bfccb27f-181d-45e1-a320-2c9b543ca800)


![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/4f7b59fe-874f-4ac8-8359-6ebf1040261b)

Database: 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/5be89021-3c36-46c5-8ede-388e3bcca0b1)

Using the search button 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/90056a6b-47bd-4be5-a173-46738358451d)

Proof of search button working as it is shown in url
![image](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/97c44bf2-3a40-4f85-96d6-990d60094459)
