### ISSUE TITLE
 Incorrect Placement of "Staff Login" Text on UI

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#55]
**Description:**
The "Staff Login" text is incorrectly positioned on the left side of the page, whereas it should be at the top.

**Expected Behavior:**
The text should appear at the top of the page to maintain consistency with the design layout.

**Steps to Reproduce:**
Go to the Staff Login Page.
Observe the placement of the "Staff Login" text.

**Screenshot:** 
![image (5) (1)](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/835ecb02-f6ad-4154-a0f7-2031c2f0fc96)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This might be due to recent UI changes in the login section.

**Comment by Brabim21** [comment]
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/1ef4a1bc-4eaa-409f-a1c7-316d4a2ea461)
The text now appears at the top of the page to maintain consistency with the design layout.
