### ISSUE TITLE
Misalignment of Edit Staff Details Form

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#56]
**Description:**
The Edit Staff Details Form is not centered on the page, causing visual inconsistency and poor user experience. Additionally, the cross button is misaligned with the form itself.

**Expected Behavior:**
The form should be centrally positioned with the cross button correctly aligned.

**Steps to Reproduce:**
Navigate to the Staff Details section.
Click on the Edit button.

**Screenshot:**
![Screenshot 2024-05-12 223850](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/2fe1246c-901f-4a90-b9e7-d5d38624a2a2)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This issue might be related to recent changes in the frontend layout or CSS styles.

**Comment by Brabim21** [comment]
![Screenshot 2024-05-12 232811](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/5abd238d-2909-4ac9-9d65-6db6db91e9b9)
The form is centrally positioned with the cross button correctly aligned.
