### ISSUE TITLE
Simultaneous Activation of Dashboard and Logo

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#57]
**Description:**
Clicking on the dashboard also triggers a click on the HMS logo, which should not happen as only the dashboard is intended to be clickable.

**Expected Behavior:**
Clicking the dashboard should only activate dashboard-related actions.

**Steps to Reproduce:**
Attempt to click on the Dashboard.

**Screenshot:**
![Screenshot 2024-05-12 232915](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/fb17c1d1-df4a-4748-9577-c5d49a6392e7)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This issue might be related to the frontend implementation of event listeners or HTML structure. It's essential to ensure that only the dashboard element is configured with the click event listener to prevent unintended interactions with other elements, such as the HMS logo.

**Comment by Brabim21** [comment]
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/0f63414c-7d35-4d16-88a4-ac8c5b968343)
Now when clicking the dashboard should only activate dashboard-related actions.
