### ISSUE TITLE
Staff Dashboard Logo Not Loading

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#58]
**Description:**
The image/logo of staff is not visible on the staff's dashboard. It fails to load, resulting in a broken image icon.

**Expected Behavior:**
The staff's logo should be displayed correctly on the dashboard, providing visual identification for each staff member.

**Steps to Reproduce:**
Log in as a staff member.
Navigate to the staff's dashboard section.

**Screenshot:**
![image (4) (1)](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/92253776-cb93-4c36-97a3-75ab754ec4b9)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
Review any recent changes to icon loading logic or backend services that could be impacting the loading of staff icons.

**Comment by Brabim21** [comment]
![Screenshot 2024-05-20 034332](https://github.com/Brabim21/Hostel_Management_System/assets/119724645/0bb4f686-9af4-490c-a4b1-382925a9190b)
Now the icon for staff is visible. This bug was found due to typo error in the name of image.
