### ISSUE TITLE
Email Update Not Reflected in Database

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#59]
**Description:**
When changing the email in the user profile section, the updated email does not reflect in the database, resulting in the user profile not being updated.

**Expected Behavior:**
Upon updating the email in the user profile, the new email address should be correctly updated and reflected in the database.

**Steps to Reproduce:**
Navigate to the User Profile section.
Change the email and submit the update.
Check the database to verify if the update has been recorded.

**Screenshots:** 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/af5151af-ab74-4555-9214-15a5864115b5)

![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/2ec7f4fd-3187-4605-bfe9-ea89e224bcc1)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This issue may relate to the backend service handling the update operations not committing changes to the database. Ensure that transactions are committed after updates.

**Comment by SwatantraNp1** [comment]
Issue solved
