### ISSUE TITLE
Redirect to Dashboard After Sending Chat Message

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#60]
**Description:**
In the 'Chat with Admin' section, after sending a message, the user is unexpectedly redirected to the dashboard instead of staying on the chat page.

**Expected Behavior:**
After sending a chat message, the user should remain on the chat page to view or continue the conversation.

**Steps to Reproduce:**
Go to the 'Chat with Admin' section.
Send a message to the admin.
Observe the redirection to the dashboard.

**Screenshot:** 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/32702104-54b0-4d39-9a7e-192538a4c2ec)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
The issue could be caused by an erroneous redirect command or event handling in the chat system. Checking the event listeners and the execution flow post-message submission will be essential.

**Comment by SwatantraNp1** [comment]
Issue solved
