### ISSUE TITLE
Staff Details Overlay Page Does Not Scroll

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#61]
**Description:**
When attempting to update staff details, the overlay modal does not scroll, preventing users from accessing lower fields in the form.

**Expected Behavior:**
The overlay page should allow scrolling to view and interact with all form fields.

**Steps to Reproduce:**
Go to the Staff Management section.
Select a staff member to edit.
Try scrolling through the overlay page that appears.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/22395350-1c95-47aa-90dc-7a925b1fca1e)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This issue may be related to the CSS overflow properties or JavaScript that affects the modal's scroll behavior.

**Comment by Ganeshparajuli2059** [comment]
Now the update overlay works properly also show password option is given. 
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/7521debb-c465-4502-924f-92ea3383c9d1)
