### ISSUE TITLE
Total Billing Amount Fetch Error

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#62]
**Description:**
The total amount in the Total Billing section does not fetch correctly, showing an error or incorrect data.

**Expected Behavior:**
The total billing amount should correctly display the sum of all relevant transactions.

**Steps to Reproduce:**
Navigate to the Billing section.
Observe the total amount display.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/b1a7e23f-ba09-4e8c-88c6-ef320c2c8f22)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context**:
This may be due to a backend fetch operation failing or errors in the query used to aggregate the total.

**Comment by Ganeshparajuli2059** [comment]
Now the total amount is fetched properly from the database and works properly as well

![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/37a41ab9-ca3b-45c1-8f99-a398246dc337)
