### ISSUE TITLE
Conditional Functionality of Update Payment Search Button

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#63]
**Description:**
The search button in the Update Payment section does not function unless the upper search button is first clicked and then the lower button is clicked again; otherwise, it displays "no user."

**Expected Behavior:**
The search button should function independently to find users without requiring multiple button presses.

**Steps to Reproduce:**
Navigate to the Payment Update section.
Attempt to use the search button without first using the upper search button.

**Screenshots:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/ba9bf9cc-110b-43e3-9ec3-0ea567708dea)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
Likely a JavaScript issue where the state or data isn't correctly updated until after the first search is triggered.

**Comment by Ganeshparajuli2059** [comment]
As of now update search button was not working so to resolve that problem i removed that section i adjusted them into the table now all the button works properly and even data get updated.
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119146652/9839971b-f634-4043-8653-03adaa2cf48d)
