### ISSUE TITLE
 Delete Option Not Working in Event Calendar

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#64]
**Description:**
The delete option in the event calendar is not functional; events cannot be deleted.

**Expected Behavior:**
Clicking on the delete option should remove the selected event from the calendar.

**Steps to Reproduce:**
Navigate to the event calendar.
Attempt to delete an event.
Observe that the delete option does not remove the event.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/bd37e35b-c81f-407f-ac9f-08aa42bbd309)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Details:**
This issue prevents users from managing their events effectively and may indicate a problem with backend event deletion logic.

**Comment by rojan-dhungel** [comment]
**The delete button is now functional**

Navigation: 
![event](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/587cb347-4072-4af8-972f-653e6050f4ca)

Adding Events : 
![eventcalender](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/05238e8e-5f0e-4a20-ab13-c83ed196729c)

Deleting Events:
![deletingeventt](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/0993cdcd-3989-4716-98f4-d3d74c340b3e)
