### ISSUE TITLE
Logout Functionality Not Working

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#65]
**Description:**
Logout functionality is not working as expected; users are not successfully logged out of the system.

**Expected Behavior:**
Clicking on the logout button should successfully log the user out of the system and return them to the login screen.

**Steps to Reproduce:**
Attempt to log out of the system.
Observe that the system does not log the user out or return to the login screen.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/12bf5dd1-6389-45e2-badf-a0df9d174e1c)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Details:**
This issue poses a security risk and impacts user privacy and session management.

**Comment by rojan-dhungel** [comment]
**The logout function is now functional**

This is the dashboard photo 
![dashboard](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/d30efa86-c700-4d08-973f-1c46ccb4178f)

This is the interface after pressing logout at the side of the navbar
![login](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/8394a1d2-9f13-4e28-9776-1ee6c886257a)
