### ISSUE TITLE
 Database Connectivity Issue in Assigned Room Name and User Status

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#66]
**Description:**
There is a database connectivity issue causing discrepancies between assigned room names and user statuses.

**Expected Behavior:**
Assigned room names and user statuses should be accurately reflected based on the database records.

**Steps to Reproduce:**
Assign a room to a user.
Check the assigned room name and user status.
Observe inconsistency or incorrect data.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/b3625302-5b61-4b5c-9efe-ef795f99abda)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Details:**
This issue may involve incorrect database queries or data mapping in the backend system.

**Comment by rojan-dhungel** [comment]
Addition of Assigned room name and user status: 
![residentinfo](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/28cf127f-a02b-4b0e-bd65-64424f245bce)
