### ISSUE TITLE
Resident and Event Count Malfunctioning in Dashboard

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#67]
**Description:**
The resident and event count displayed in the dashboard is malfunctioning, showing incorrect or inconsistent values.

**Expected Behavior:**
The resident and event counts in the dashboard should accurately reflect the current number of residents and events in the system.

**Steps to Reproduce:**
Navigate to the dashboard section.
Observe the displayed resident and event counts.

**Screenshots:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/e355cea6-0924-4b40-b0df-00ba5e275396)
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/0e32a3c1-cdbe-4645-9381-432678cef53b)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Details:**
The incorrect counts may lead to misinformation for users and affect decision-making processes based on dashboard data.
This issue could be related to data retrieval or calculation errors in the backend system.

**Comment by rojan-dhungel** [comment]
**Event Count issue has been solved** 
**Below are the screenshots attached:** 


![event](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/1d230afc-e6f8-49ac-ae25-f0389756bcea)
![eventcalender](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/318a785e-a39b-41e0-86aa-e91b28dff17f)

**Resident Information issue has been solved** 
**Below are the screenshots attached:** 
  
![residentinfo](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/8a5a30ee-6069-4b4b-b51c-a7aa89e843d2)
![residentcount](https://github.com/Brabim21/Hostel_Management_System/assets/120009180/d66f1bee-fb1e-4010-a678-cf93bbc17807)
 

The malfunctioning of both the Event Calendar and Resident Information.
