### ISSUE TITLE
 Payment Functionality for eSewa and NMB Bank Fails to Proceed

### ISSUE THREAD

**Issue by Alishapokharel1** [Brabim21/Hostel_Management_System#77]
**Description:**
Residents attempting to pay fees using eSewa or NMB Bank encounter an issue where the payment process does not proceed beyond the selection of the payment method, preventing the completion of the transaction.

**Steps to Reproduce:**
Log in as a resident and access the resident dashboard.
Click on the "Pay Fee" option.
Select eSewa or NMB Bank as the payment method.
- For eSewa: Enter valid payment details and attempt to complete the payment process.
- For NMB Bank: Enter invalid payment details and attempt to complete the payment process.

**Expected Behavior:**
For eSewa: A confirmation message should be displayed indicating successful payment, and a receipt should be generated.
For NMB Bank: An error message should be displayed indicating that the payment details are invalid.

**Actual Behavior:**
The selection leads to options for eSewa and NMB Bank, but the functionality does not proceed beyond this point, preventing the completion of the payment process.

**Screenshot:**
![image](https://github.com/Brabim21/Hostel_Management_System/assets/119913387/93a38fe0-98e3-43c7-850b-b03dac0776ca)

**Environment:**
Browser: Google Chrome 124.0.6367.201
OS: Windows 11 Home, Version 22H2, OS Build 22621.2361

**Additional Context:**
This issue prevents residents from completing their payments using either eSewa or NMB Bank, impacting the overall user experience and fee collection process. The inability to proceed beyond the payment method selection is a critical failure that needs to be addressed promptly.

**Comment by SwatantraNp1** [comment]
![image](https://github.com/Brabim21/Hostel_Management_System/assets/127380630/d0212cfd-a4fc-4ae2-907c-b727a6fb6b63)
![image](https://github.com/Brabim21/Hostel_Management_System/assets/127380630/5ba21265-e666-4909-9b2e-35c519fa15e8)
![image](https://github.com/Brabim21/Hostel_Management_System/assets/127380630/5b3bc303-f6fa-4649-b25b-d342b5cb8034)


The function for payment has been added
